app:
    name: BSRIInsurance
    title: 'BSRI Insurance'
    description: 'Insurance OI Application'
    category: Dashboards
    type: 2
    autostart: 'true'
    uuid: c1f756bf-b91a-460a-994c-7afa7c8d52e3
    isdefault: false
    logo: default_app.png
    status: 4
    start_options: null
checkOrg: true    
org:
    name: BSRI
    uuid: c01056d8-e2f7-4b98-964a-3f868fb1ed2f
    email: bsriuseradmin@vantageagora.com
    address1: '2113 Greenbriar Drive'
    address2: 'Suite D, Southlake'
    city: Southlake
    state: Texas
    zip: 76092
    contact:
        username: bsriuser
        firstname: BSRI
        lastname: USer
        email: bsriuser@vantageagora.com
    preferences: '{"dateformat":"MM-dd-yyyy","currency":"USD","timezone":"America/New_York"}'
    country: 'United States of America'
privilege:
    -
        name: MANAGE_AGENTVIEW
        permission: 15
    -
        name: MANAGE_UNDERWRITERVIEW
        permission: 15
    -
        name: MANAGE_PRODUCTIONVIEW
        permission: 15
    -
        name: MANAGE_BAMREPORTVIEW
        permission: 15
role:
    -
        name: 'BSRI Agent'
        privilegesDuplicate:
            -
                privilege_name:
                    name: MANAGE_AGENTVIEW
                    permission: 15
                permission: 15
        default: true
        privileges:
            -
                privilege_name: MANAGE_AGENTVIEW
                permission: 15
        uuid: 6c6ecfb6-07af-474a-a873-d8a61a4f7444
    -
        name: 'BSRI Underwriter'
        privilegesDuplicate:
            -
                privilege_name:
                    name: MANAGE_UNDERWRITERVIEW
                    permission: 15
                permission: 15
        default: true
        privileges:
            -
                privilege_name: MANAGE_UNDERWRITERVIEW
                permission: 15
        uuid: 1ffecc5f-bb10-425f-8ef2-7474ad7d3ff3
    -
        name: 'BSRI Production'
        privilegesDuplicate:
            -
                privilege_name:
                    name: MANAGE_PRODUCTIONVIEW
                    permission: 15
                permission: 15
        default: true
        privileges:
            -
                privilege_name: MANAGE_PRODUCTIONVIEW
                permission: 15
        uuid: ee4eb6da-50bb-42b1-a930-b847986e7d5f
    -
        name: 'BSRI BAM'
        privilegesDuplicate:
            -
                privilege_name:
                    name: MANAGE_BAMREPORTVIEW
                    permission: 15
                permission: 15
        default: true
        privileges:
            -
                privilege_name: MANAGE_BAMREPORTVIEW
                permission: 15
        uuid: 7ce12c65-0168-48b9-b912-5ad8661a157d
pages:
    -
        page_name: BSRIManagerProductionOIPage.yml
        uuid: d7cf66d2-d2d6-4897-b8d1-c17aebb35bda
    -
        page_name: BSRIManagerUnderwriterOIPage.yml
        uuid: feabeb18-f4dc-48af-b078-31c16d1aea0c
    -
        page_name: BSRIManagerAgentOIPage.yml
        uuid: f0460cc9-38f9-408d-b51b-cfe05128e076
    -
        page_name: BSRIManagerBAMOIPage.yml
        uuid: 974ae3fb-c1ff-40b2-b584-f276e00a8239
menu:
    -
        name: Agent
        icon: 'fal fa-address-card'
        privilege: MANAGE_AGENTVIEW_WRITE
        page_uuid: f0460cc9-38f9-408d-b51b-cfe05128e076
        uuid: 21bff526-c39a-4d8b-a605-86c34b0a804d
    -
        name: Underwriter
        icon: 'fad fa-user-edit'
        privilege: MANAGE_UNDERWRITERVIEW_WRITE
        page_uuid: feabeb18-f4dc-48af-b078-31c16d1aea0c
        uuid: c1a13288-fd25-4287-b01a-7300d81319ff
    -
        name: Production
        icon: 'fal fa-funnel-dollar'
        privilege: MANAGE_PRODUCTIONVIEW_WRITE
        page_uuid: d7cf66d2-d2d6-4897-b8d1-c17aebb35bda
        uuid: bc0b8879-b21c-4782-9fa6-f550e6f6e92d
    -
        name: BAM
        icon: 'fal fa-truck-moving'
        privilege: MANAGE_BAMREPORTVIEW_WRITE
        page_uuid: 974ae3fb-c1ff-40b2-b584-f276e00a8239
        uuid: 38392c31-a786-4ffa-b9a1-31b20e873980
