app:
    -
        name: Insurance
        uuid: f726fded-0764-4f4e-945e-689586baf74b
        description: 'Insurance OI Application'
        category: Dashboards
        type: 2
        autostart: 'true'
org:
    -
        name: 'EOX Vantage1'
        uuid: b0923de7-0387-48ea-8f29-5d3704d96a46
        email: helpdesk@vantageagora.com
        address1: '23611 Chagrin Blvd, Ste 320'
        address2: 'Beachwood, Ohio 44122'
        city: Beachwood
        state: OH
        zip: 44122
        contact:
            username: supportadmin
            firstname: Support
            lastname: Admin
            email: helpdesk@vantageagora.com
        preferences: '{}'
        country: 'United States'
privilege:
    -
        name: MANAGE_AGENTVIEW
        permission: 15
    -
        name: MANAGE_MANAGERVIEW
        permission: 15
role:
    -
        name: 'Insurance Agent'
        default: true
        privileges:
            -
                privilege_name: MANAGE_AGENTVIEW
                permission: 15
        uuid: c066efa8-09d4-4fc5-b5c3-89024becec86
    -
        name: 'Insurance Manager'
        default: true
        privileges:
            -
                privilege_name: MANAGE_MANAGERVIEW
                permission: 15
        uuid: a6745b11-9aa4-45f1-81c2-92deaba95171
pages:
    -
        page_name: ManagerProductionOIPage.yml
        uuid: 356ab802-2de7-4b5b-a76e-97a863e1332b
    -
        page_name: ManagerUnderwriterOIPage.yml
        uuid: 1dee3f2e-9952-4390-9d42-904d28b9f91f
    -
        page_name: ManagerAgentOIPage.yml
        uuid: 68e1c30c-9bfd-456a-a99b-da4fc80b9186
menu:
    -
        name: Agent
        icon: 'fal fa-address-card'
        privilege: MANAGE_MANAGERVIEW_WRITE
        page_uuid: 68e1c30c-9bfd-456a-a99b-da4fc80b9186
        uuid: e9d94c64-358e-4174-8748-aef23623c2d6
    -
        name: Underwriter
        icon: 'fad fa-user-edit'
        privilege: MANAGE_MANAGERVIEW_WRITE
        page_uuid: 1dee3f2e-9952-4390-9d42-904d28b9f91f
        uuid: 234e4f1b-1e44-40f3-a944-3a9b89d855a5
    -
        name: Production
        icon: 'fal fa-funnel-dollar'
        privilege: MANAGE_MANAGERVIEW_WRITE
        page_uuid: 356ab802-2de7-4b5b-a76e-97a863e1332b
        uuid: d02ffb8f-a3ae-476a-a85f-198dd73359ac